<?php
// This file is autogenerated by Composer. Do not edit
return array (
  0 => 'Inpsyde\\Debug\\InpsydeDebugModule',
  1 => 'Inpsyde\\Http\\HttpClientModule',
  2 => 'Inpsyde\\WcEvents\\WcEventsModule',
  3 => 'Inpsyde\\WcStatusReport\\WcStatusReportModule',
  4 => 'Inpsyde\\Zettle\\Assets\\AssetsModule',
  5 => 'Inpsyde\\Zettle\\Logging\\ZettleLoggingModule',
  6 => 'Inpsyde\\Zettle\\Notices\\NoticesModule',
  7 => 'Inpsyde\\Zettle\\PhpSdk\\PhpSdkModule',
  8 => 'Inpsyde\\Zettle\\Auth\\AuthModule',
  9 => 'Inpsyde\\StateMachine\\StateMachineModule',
  10 => 'Inpsyde\\Zettle\\Onboarding\\OnboardingModule',
  11 => 'Inpsyde\\Zettle\\ProductDebug\\ProductDebugModule',
  12 => 'Inpsyde\\Zettle\\ProductSettings\\ProductSettingsModule',
  13 => 'Inpsyde\\Zettle\\Queue\\ZettleQueueModule',
  14 => 'Inpsyde\\Zettle\\Settings\\SettingsModule',
  15 => 'Inpsyde\\Zettle\\Sync\\SyncModule',
  16 => 'Inpsyde\\Queue\\QueueModule',
  17 => 'Inpsyde\\Zettle\\Webhooks\\WebhookModule',
  18 => 'Inpsyde\\Zettle\\PluginModule',
);